apiVersion: apps/v1
kind: Deployment
metadata:
  name: complexity
  labels:
    app: complexity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complexity
  template:
    metadata:
      labels:
        app: complexity
    spec:
      containers:
      - name: complexity
        image: youseq/complexity:v1.0.0
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: complexity
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: complexity-service
spec:
  selector:
    app: complexity
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: complexity-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: complexity
  updatePolicy:
    updateMode:  Recreate
