apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineageservice
  labels:
    app: lineageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lineageservice
  template:
    metadata:
      labels:
        app: lineageservice
    spec:
      containers:
      - name: lineageservice
        image: youseq/lineageservice:v1.0.0
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lineageservice-service
spec:
  selector:
    app: lineageservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
