apiVersion: apps/v1
kind: Deployment
metadata:
  name: msaaligner
  labels:
    app: msaaligner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msaaligner
  template:
    metadata:
      labels:
        app: msaaligner
    spec:
      containers:
      - name: msaaligner
        image: youseq/msa_aligner:latest
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: msa_aligner
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: includesexcludes_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: msaaligner-service
spec:
  selector:
    app: msaaligner
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
