apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share
  labels:
    bucket: shared
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: "192.168.1.64"
    path: "/share/bioinformatics/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nt-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      bucket: shared
