apiVersion: apps/v1
kind: Deployment
metadata:
  name: windowgen
  labels:
    app: windowgen 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: windowgen
  template:
    metadata:
      labels:
        app: windowgen
    spec:
      containers:
      - name: windowgen
        image: youseq/windowgen:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: windowgen
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        - name: NT_FILE
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: nt_filename

        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: windowgen-service
spec:
  selector:
    app: windowgen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windowgen-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: windowgen
  updatePolicy:
    updateMode:  Recreate

