apiVersion: apps/v1
kind: Deployment
metadata:
  name: alignmentfilter
  labels:
    app: alignmentfilter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alignmentfilter
  template:
    metadata:
      labels:
        app: alignmentfilter
    spec:
      containers:
      - name: alignmentfilter
        image: youseq/alignment_filter:latest
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: alignmentfilter
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        - name: NT_FILE
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: nt_filename

        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alignmentfilter-service
spec:
  selector:
    app: alignmentfilter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
