apiVersion: apps/v1
kind: Deployment
metadata:
  name: blastsearcher
  labels:
    app: blastsearcher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blastsearcher
  template:
    metadata:
      labels:
        app: blastsearcher
    spec:
      containers:
      - name: blastsearcher
        image: youseq/blastsearcher:latest
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: msaaligner_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: blastsearcher-service
spec:
  selector:
    app: blastsearcher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

