apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterservice
  labels:
    app: clusterservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterservice
  template:
    metadata:
      labels:
        app: clusterservice
    spec:
      containers:
      - name: windowgen
        image: youseq/clusterservice:latest
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
      volumes:
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: clusterservice-service
spec:
  selector:
    app: clusterservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

