apiVersion: apps/v1
kind: Deployment
metadata:
  name: complexity
  labels:
    app: complexity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complexity
  template:
    metadata:
      labels:
        app: complexity
    spec:
      containers:
      - name: complexity
        image: youseq/complexity:latest
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: complexity-service
spec:
  selector:
    app: complexity
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
