apiVersion: apps/v1
kind: Deployment
metadata:
  name: datafinder
  labels:
    app: datafinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datafinder
  template:
    metadata:
      labels:
        app: datafinder
    spec:
      containers:
      - name: datafinder
        image: youseq/datafinder:latest
        resources:
          requests:
            memory: "50Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: datafinder-service
spec:
  selector:
    app: datafinder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#apiVersion: autoscaling.k8s.io/v1
#kind: VerticalPodAutoscaler
#metadata:
#  name: datafinder-vpa
#spec:
#  targetRef:
#    apiVersion: "apps/v1"
#    kind: Deployment
#    name: datafinder
#  updatePolicy:
#    updateMode:  Recreate
