apiVersion: apps/v1
kind: Deployment
metadata:
  name: datafinder
  labels:
    app: datafinder
spec:
  #replicas: 0
  selector:
    matchLabels:
      app: datafinder
  template:
    metadata:
      labels:
        app: datafinder
    spec:
      containers:
      - name: datafinder
        image: youseq/datafinder:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: datafinder
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: datafinder-service
spec:
  selector:
    app: datafinder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: keda-rabbitmq-secret
#data:
#  host: YW1xcDovL3Rlc3Q6dGVzdEByYWJiaXRtcS1jbHVzdGVyLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLWNsdXN0ZXIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QDE5Mi4xNjguMC4xMzA6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLWNsdXN0ZXI6NTY3Mg== #YW1xcDovL3Rlc3Q6dGVzdEByYWJiaXRtcS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzIK #YW1xcDovL3Rlc3Q6dGVzdEBsb2NhbGhvc3Q6NTY3Mi92aG9zdA== # base64 encoded value of format amqp://guest:password@localhost:5672/vhost
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject-datafinder
  namespace: default
spec:
  scaleTargetRef:
    name: datafinder
  triggers:
  - type: rabbitmq
    metadata:
            #  protocol: amqp
      queueName: datafinder-current-designs
      mode: QueueLength
      value: "1"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
      #      metricName: custom-testqueue #optional. Generated value would be `rabbitmq-custom-testqueue`    authenticationRef:
      #name: keda-trigger-auth-rabbitmq-conn
