apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: youseq/auto_qpcr_frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: msaaligner_url
        volumeMounts:
        - name: pathways-file
          mountPath: /pathways/pathways.json
      volumes:
      - name: pathways-file
        hostPath:
          path: /home/ciaran/qpcr_service/pathways.json
          type: File

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000
