apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: youseq/auto_qpcr_frontend2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: msaaligner_url
        volumeMounts:
        - name: nt-volume
          mountPath: /home/ciaran/nt
          #        - name: pathways-file
          #mountPath: /pathways/pathways.json
      volumes:
#      - name: pathways-file
#        hostPath:
#          path: /home/ciaran/qpcr_service/pathways.json
#          type: File
      - name: nt-volume
        persistentVolumeClaim:
          claimName: nt-pvc



---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000
---
#apiVersion: autoscaling.k8s.io/v1
#kind: VerticalPodAutoscaler
#metadata:
#  name: fronend-vpa
#spec:
#  targetRef:
#    apiVersion: "apps/v1"
#    kind: Deployment
#    name: frontend
#  updatePolicy:
#    updateMode:  Initial
