apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL3Rlc3Q6dGVzdEByYWJiaXRtcS1jbHVzdGVyLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLWNsdXN0ZXIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QDE5Mi4xNjguMC4xMzA6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
  #YW1xcDovL2RlZmF1bHRfdXNlcl9QeUxFVTNmTGtfanlJTUc1WDJKOnVmWUZ6ZzJFMU9raGUtclJkM3dFVzlaekw0U0Z2ekQ3QHJhYmJpdG1xLWNsdXN0ZXI6NTY3Mg== #YW1xcDovL3Rlc3Q6dGVzdEByYWJiaXRtcS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzIK #YW1xcDovL3Rlc3Q6dGVzdEBsb2NhbGhvc3Q6NTY3Mi92aG9zdA== # base64 encoded value of format amqp://guest:password@localhost:5672/vhost

