kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraMounts:
  - hostPath: /home/ciaran/taxid2accession/taxid2accession 
    containerPath: /home/ciaran/taxid2accession/taxid2accession
  - hostPath: /home/ciaran/qpcr_service/pathways.json
    containerPath: /home/ciaran/qpcr_service/pathways.json
- role: worker
  extraMounts:
  - hostPath: /home/ciaran/taxid2accession/taxid2accession
    containerPath: /home/ciaran/taxid2accession/taxid2accession
  - hostPath: /home/ciaran/qpcr_service/pathways.json
    containerPath: /home/ciaran/qpcr_service/pathways.json
