apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdd
  labels:
    app: pdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdd
  template:
    metadata:
      labels:
        app: pdd
    spec:
      containers:
      - name: pdd
        image: youseq/pdd:latest
        ports:
        - containerPort: 80
        env:
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: pdd-service
spec:
  selector:
    app: pdd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

