apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdd
  labels:
    app: pdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdd
  template:
    metadata:
      labels:
        app: pdd
    spec:
      nodeName: 'jackie-weaver'
      containers:
      - name: pdd
        image: youseq/pdd:latest
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: exchange_name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_host
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: rabbitmq_password
        - name: RABBITMQ_LISTEN_QUEUE
          value: pdd
        - name: NEXT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: priorityq_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url
---
apiVersion: v1
kind: Service
metadata:
  name: pdd-service
spec:
  selector:
    app: pdd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

