apiVersion: apps/v1
kind: Deployment
metadata:
  name: priorityq
  labels:
    app: priorityq 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priorityq
  template:
    metadata:
      labels:
        app: priorityq
    spec:
      containers:
      - name: priorityq
        image: youseq/priorityq:latest
        ports:
        - containerPort: 80
        env:
        - name: WINDOW_GEN_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: windowgen_url
        - name: COMPLEXITY_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: complexity_url
        - name: BLAST_SEARCHER_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: blastsearcher_url
        - name: MSA_ALIGNER_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: msaaligner_url
        - name: INCLUDESEXCLUDES_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: includesexcludes_url
        - name: KIT_SELECTOR_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: kitselector_url
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: qpcr-configmap
              key: frontend_url

---
apiVersion: v1
kind: Service
metadata:
  name: priorityq-service
spec:
  selector:
    app: priorityq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

